version: '1'


services:
  wordpress:
    container-name: frontend-network
    image: wordpress:latest
    ports:
      - "80:443"
    env_file:
      - .env
    depends_on:
      - db
      - phpmyadmin
    restart: always
    networks:
      backend_network:
        ipv4_address: 192.168.10.10
      frontend_network:
        ipv4_address: 192.168.20.10
      hostname: frontend-network

    healthcheck:
      test: ["CMD", "curl", "-f", "http://google.com"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s


  db:
    container-name: backend-network
    image: mysql:latest
    env_file:
      - .env
    restart: always
    networks:
      backend_network:
        ipv4_address: 192.168.10.10
      frontend_network:
        ipv4_address: 192.168.20.10
      hostname: backend-network/database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://google.com"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
      
  phpmyadmin:
    container-name: frontend-network
    image: phpmyadmin:latest
    env_file:
      - .env
    restart: always
    depends_on:
      - db
    ports:
      - 80:80
    
    
    networks:
      backend_network:
        ipv4_address: 192.168.10.10
      frontend_network:
        ipv4_address: 192.168.20.10
      hostname: frontend-network/phpmyadmin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://google.com"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5sQ
    

  networks:
    backend_network:
        ipam:
            config:
              - subnet: 192.168.10.0/24
    red_interna:
        ipam:
            config:
              - subnet: 192.168.20.0/24